[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
  [[module.mounts]]
    source = "content/en"
    target = "content"
    lang = "en"

baseURL = "https://goa.design/"
title = "Goa"
theme = "docsy"
enableGitInfo = true
enableRobotsTXT = true

# Language configuration
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableLanguages = []

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ja]
    languageName = "日本語 (Japanese)"
    weight = 2
  [languages.it]
    languageName = "Italiano (Italian)"
    weight = 3

# Navigation menu configuration
[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 1
  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 2

[params]
  docsy_sections = ["docs"]

  # Home page features section configuration
  [[params.features]]
    id = "codegen"
    color = "#ED3E3E"
    icon = "fa-wand-magic-sparkles"
  [[params.features]]
    id = "design"
    color = "#80AD00"
    icon = "fa-pencil"
  [[params.features]]
    id = "best_practice"
    color = "#5DB9F2"
    icon = "fa-star"
  
  # Home page sponsors section configuration
  [[params.sponsors]]
    id = "incidentio"
    name = "incident.io"
    image = "/img/sponsors/incidentio.png"
    url = "https://incident.io"
  [[params.sponsors]]
    id = "speakeasy"
    name = "Speakeasy"
    image = "/img/sponsors/speakeasy.png"
    url = "https://www.speakeasyapi.dev/docs/api-frameworks/goa?utm_source=goa+repo&utm_medium=github+sponsorship"

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      # Redirect /docs/* to /en/docs/* when language not specified
      [[server.headers.values.Link]]
        rel = "alternate"
        hreflang = "x-default"
        href = "/en{path}"